### ISSUE TITLE
Does not work with an ogg flac stream

### ISSUE THREAD

**Issue by Prikith** [dennizzzz/castnow#2]
## Expected Behavior
Using castnow with an ogg flac stream from an icecast source should play the stream correctly
## Current Behavior
The application errors out with
```
/opt/castnow/node_modules/music-metadata/lib/ogg/OggParser.js:78
                           throw new Error('gg audio-codec not recognized (id=' + id + ')')
;
                                 ^

Error: gg audio-codec not recognized (id=FLAC)
   at OggParser.parse (/opt/castnow/node_modules/music-metadata/lib/ogg/OggParser.js:78:35)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   at async parse (/opt/castnow/node_modules/music-metadata/lib/ParserFactory.js:38:5) 
```

**Comment by dennizzzz** [comment]
Hmm, this probably has to do with an ancient version of music-metadata. I was in the process of upgrading dependencies anyway, but I can probably squeeze this one in soon.
